Repository flyteorg/flytekit, pull requests merged in 2024-07, with the labels that each got.

#2346 Adds a Default ImageSpec image builder
  flytekit/image_spec/__init__.py
  flytekit/image_spec/default_builder.py
  plugins/flytekit-envd/tests/test_image_spec.py
  tests/flytekit/unit/core/image_spec/test_default_builder.py
Labels: size:L

#2314 Core/enable deck
  flytekit/core/base_task.py
  flytekit/core/context_manager.py
  flytekit/core/python_function_task.py
  flytekit/core/task.py
  flytekit/deck/__init__.py
  flytekit/deck/deck.py
  tests/flytekit/unit/core/test_utils.py
  tests/flytekit/unit/deck/test_deck.py
Labels: size:L

#2543 Feat: Improve UX of pytorch-elastic plugin by configuring reasonable defaults
  plugins/flytekit-kf-pytorch/flytekitplugins/kfpytorch/pod_template.py
  plugins/flytekit-kf-pytorch/flytekitplugins/kfpytorch/task.py
  plugins/flytekit-kf-pytorch/setup.py
  plugins/flytekit-kf-pytorch/tests/test_elastic_task.py
  plugins/flytekit-kf-pytorch/tests/test_shared.py
Labels: enhancement

#2594 Feat: Make exception raised by external command authenticator more actionable
  flytekit/clients/auth/authenticator.py
Labels: Improve error handling

#2228 Remove pyarrow as a direct dependency
  .github/workflows/pythonbuild.yml
  dev-requirements.in
  pyproject.toml
  tests/flytekit/unit/core/test_type_engine.py
  tests/flytekit/unit/deck/test_renderer.py
  tests/flytekit/unit/lazy_module/test_lazy_module.py
  tests/flytekit/unit/types/structured_dataset/test_arrow_data.py
  tests/flytekit/unit/types/structured_dataset/test_structured_dataset.py
  tests/flytekit/unit/types/structured_dataset/test_structured_dataset_handlers.py
  tests/flytekit/unit/types/structured_dataset/test_structured_dataset_workflow.py
  tests/flytekit/unit/types/structured_dataset/test_structured_dataset_workflow_with_nested_type.py
Labels: size:M
