Repository flyteorg/flytekit, pull requests merged in 2024-03, with the labels that each got.

#2225 Use disk-space-reclaimer only when running envd tests
  .github/workflows/pythonbuild.yml
Labels: lgtm, size:XS

#2212 Dep: Pin grpcio in flytekit-identity-aware-proxy to version that allo…
  plugins/flytekit-identity-aware-proxy/setup.py
Labels: lgtm, size:XS

#2176 Fix: Handle overriding of container image in backend
  flytekit/core/node.py
  flytekit/models/core/workflow.py
  flytekit/tools/translator.py
  tests/flytekit/unit/core/test_array_node_map_task.py
  tests/flytekit/unit/core/test_map_task.py
  tests/flytekit/unit/core/test_node_creation.py
Labels: bug, lgtm, size:M

#2230 Fixes failing test related to TaskNodeOverrides
  flytekit/models/core/workflow.py
Labels: lgtm, size:XS

#2209 ci(build-image): Fix incomplete double quote in yaml file
  .github/workflows/build_image.yml
Labels: lgtm, size:XS

#2231 Add agent slim image
  .github/workflows/pythonpublish.yml
  Dockerfile.agent
Labels: lgtm, size:M

#2232 Add health check servicer for agent
  Dockerfile.agent
  flytekit/clis/sdk_in_container/serve.py
Labels: lgtm, size:M

#2224 Dynamic partition setting
  flytekit/bin/entrypoint.py
  flytekit/core/artifact.py
  flytekit/core/artifact_utils.py
  flytekit/core/base_task.py
  flytekit/core/context_manager.py
  flytekit/core/interface.py
  flytekit/core/promise.py
  flytekit/core/sentinel.py
  flytekit/tools/translator.py
  pyproject.toml
  tests/flytekit/unit/core/test_artifacts.py
Labels: size:L

#2226 ChatGPT Agent
  .github/workflows/pythonbuild.yml
  Dockerfile.agent
  flytekit/extend/backend/base_agent.py
  plugins/flytekit-openai/README.md
  plugins/flytekit-openai/flytekitplugins/chatgpt/__init__.py
  plugins/flytekit-openai/flytekitplugins/chatgpt/agent.py
  plugins/flytekit-openai/flytekitplugins/chatgpt/task.py
  plugins/flytekit-openai/setup.py
  plugins/flytekit-openai/tests/test_agent.py
  plugins/flytekit-openai/tests/test_chatgpt.py
Labels: lgtm, size:L

#2214 Add `--overwrite-cache` in `pyflyte backfill` cli
  flytekit/clis/sdk_in_container/backfill.py
  flytekit/remote/remote.py
Labels: lgtm, size:S

#2235 Fix Monodocs build
  .github/workflows/monodocs_build.yml
  flytekit/extend/backend/base_agent.py
  plugins/flytekit-bigquery/flytekitplugins/bigquery/agent.py
Labels: lgtm, size:M

#2223 Enhance default image to check FLYTE_INTERNAL_IMAGE
  flytekit/configuration/__init__.py
  flytekit/configuration/default_images.py
Labels: lgtm, size:XS

#2233 wip
  flytekit/core/artifact.py
  flytekit/core/artifact_utils.py
  flytekit/core/base_task.py
  flytekit/core/card.py
  flytekit/core/context_manager.py
  flytekit/core/data_persistence.py
  flytekit/models/literals.py
  tests/flytekit/unit/core/test_artifacts.py
  tests/flytekit/unit/core/test_card.py
  tests/flytekit/unit/core/test_data_persistence.py
  tests/flytekit/unit/models/test_literals.py
Labels: size:L

#2240 Remove trailing '=' character from generated image tag hash value
  flytekit/image_spec/image_spec.py
  tests/flytekit/unit/cli/pyflyte/test_run.py
  tests/flytekit/unit/core/image_spec/test_image_spec.py
Labels: lgtm, size:S

#2243 Simpler dev images
  Dockerfile.dev
  Makefile
Labels: lgtm, size:S

#2245 Only have one flyteidl entry in pyproject toml
  pyproject.toml
Labels: lgtm, size:XS

#2210 DOCS-301 update flytekit links to monodocs
  README.md
  flytekit/clis/flyte_cli/main.py
  flytekit/clis/sdk_in_container/init.py
  flytekit/configuration/__init__.py
  flytekit/core/schedule.py
  flytekit/experimental/eager_function.py
  plugins/flytekit-aws-athena/README.md
  plugins/flytekit-aws-sagemaker/README.md
  plugins/flytekit-dask/README.md
  plugins/flytekit-dolt/README.md
  plugins/flytekit-greatexpectations/README.md
  plugins/flytekit-hive/README.md
  plugins/flytekit-huggingface/README.md
  plugins/flytekit-k8s-pod/README.md
  plugins/flytekit-kf-pytorch/README.md
  plugins/flytekit-mmcloud/README.md
  plugins/flytekit-modin/README.md
  plugins/flytekit-pandera/README.md
  plugins/flytekit-papermill/README.md
  plugins/flytekit-polars/README.md
  plugins/flytekit-snowflake/README.md
  plugins/flytekit-spark/README.md
  plugins/flytekit-sqlalchemy/README.md
  plugins/flytekit-vaex/README.md
Labels: lgtm, size:M

#2237 Define python versions a priori and schedule CI runs once a day
  .github/workflows/pythonbuild.yml
  plugins/flytekit-duckdb/setup.py
  plugins/flytekit-kf-pytorch/dev-requirements.in
  plugins/flytekit-mlflow/dev-requirements.in
  plugins/flytekit-modin/dev-requirements.in
  plugins/flytekit-modin/setup.py
  plugins/flytekit-sqlalchemy/flytekitplugins/sqlalchemy/task.py
Labels: lgtm, size:M

#2247 Simplify version calculation
  .github/workflows/pythonbuild.yml
Labels: lgtm, size:S

#2246 Adds a FlyteDeck markdown renderer to core
  flytekit/deck/__init__.py
  flytekit/deck/renderer.py
  plugins/flytekit-deck-standard/flytekitplugins/deck/renderer.py
  plugins/flytekit-deck-standard/tests/test_renderer.py
  pyproject.toml
  tests/flytekit/unit/deck/test_deck.py
Labels: lgtm, size:M

#2251 DeleteTask should return DeleteTaskResponse
  flytekit/extend/backend/agent_service.py
Labels: lgtm, size:XS

#2248 Promote source code renderer and use it by default
  flytekit/core/python_function_task.py
  flytekit/deck/__init__.py
  flytekit/deck/renderer.py
  plugins/flytekit-deck-standard/flytekitplugins/deck/renderer.py
  plugins/flytekit-deck-standard/tests/test_renderer.py
  pyproject.toml
  tests/flytekit/unit/deck/test_deck.py
Labels: lgtm, size:M

#2244 Refactor Databricks Agent Phase
  flytekit/extend/backend/utils.py
  plugins/flytekit-bigquery/flytekitplugins/bigquery/agent.py
  plugins/flytekit-spark/flytekitplugins/spark/agent.py
  plugins/flytekit-spark/tests/test_agent.py
  tests/flytekit/unit/extend/test_agent.py
Labels: lgtm, size:M

#2250 feat(resources): support serialization of Resources dataclasses
  flytekit/core/resources.py
  tests/flytekit/unit/core/test_resources.py
Labels: lgtm, size:M

#2249 Fix sql alchemy plugin error `module 'pandas.io' has no attribute 'common' `
  flytekit/types/structured/basic_dfs.py
  plugins/flytekit-sqlalchemy/setup.py
Labels: lgtm, size:XS

#2229 ShellTask: stores process return code, stdout and stderr for later use.
  flytekit/extras/tasks/shell.py
  tests/flytekit/unit/extras/tasks/test_shell.py
Labels: lgtm, size:M

#2253 Bump flyteidl for spark plugin
  plugins/flytekit-spark/setup.py
Labels: lgtm, size:XS

#2255 Rewrite test to work better on all platforms
  tests/flytekit/unit/core/test_flyte_file.py
Labels: lgtm, size:M

#2217 Support pydantic plugin in 2.xx version
  .github/workflows/pythonbuild.yml
  flytekit/interaction/click_types.py
  plugins/flytekit-pydantic/README.md
  plugins/flytekit-pydantic/flytekitplugins/pydantic/basemodel_transformer.py
  plugins/flytekit-pydantic/flytekitplugins/pydantic/deserialization.py
  plugins/flytekit-pydantic/flytekitplugins/pydantic/serialization.py
  plugins/flytekit-pydantic/tests/test_type_transformer.py
Labels: lgtm, size:M

#2208 Fix FlyteFS
  flytekit/clients/friendly.py
  flytekit/core/data_persistence.py
  flytekit/remote/remote.py
  flytekit/remote/remote_fs.py
  tests/flytekit/unit/clients/test_friendly.py
Labels: lgtm, size:L

#2261 Fix monodocs
  flytekit/core/artifact_utils.py
Labels: lgtm, size:XS

#2259 entrypoint.py: Explicitly import exit from sys
  flytekit/bin/entrypoint.py
Labels: lgtm, size:XS

#2254 Capitalize flyte deck header names
  flytekit/core/base_task.py
  flytekit/core/context_manager.py
  plugins/flytekit-kf-pytorch/tests/test_elastic_task.py
  tests/flytekit/unit/deck/test_deck.py
Labels: lgtm, size:S

#2227 Remove verbose debug message
  flytekit/clis/sdk_in_container/utils.py
Labels: lgtm, size:XS

#1890 Enable remote workflow to be invoked in conditional branch
  flytekit/remote/remote.py
  tests/flytekit/unit/remote/test_remote.py
Labels: hacktoberfest-accepted, lgtm, size:L

#2234 feat: implement force push functionality in ImageSpec
  flytekit/image_spec/image_spec.py
  tests/flytekit/unit/core/image_spec/test_image_spec.py
Labels: lgtm, size:M

#2242 Make array_node_map_task the default map_task
  dev-requirements.in
  flytekit/__init__.py
  flytekit/bin/entrypoint.py
  flytekit/core/array_node_map_task.py
  flytekit/core/legacy_map_task.py
  flytekit/core/node.py
  flytekit/experimental/__init__.py
  flytekit/tools/translator.py
  plugins/flytekit-k8s-pod/tests/test_pod.py
  tests/flytekit/unit/core/test_array_node_map_task.py
  tests/flytekit/unit/core/test_map_task.py
  tests/flytekit/unit/core/test_node_creation.py
  tests/flytekit/unit/core/test_partials.py
Labels: lgtm, size:L

#2270 Migrate over to using datetime.now(timezone.utc)
  flytekit/bin/entrypoint.py
  flytekit/core/context_manager.py
  flytekit/core/mock_stats.py
  flytekit/core/utils.py
  flytekit/experimental/eager_function.py
  flytekit/remote/remote.py
  plugins/flytekit-deck-standard/tests/test_renderer.py
  plugins/flytekit-greatexpectations/flytekitplugins/great_expectations/schema.py
  plugins/flytekit-greatexpectations/flytekitplugins/great_expectations/task.py
  plugins/flytekit-identity-aware-proxy/tests/test_flytekitplugins_iap.py
  tests/flytekit/integration/remote/test_remote.py
  tests/flytekit/unit/core/test_context_manager.py
  tests/flytekit/unit/deck/test_deck.py
  tests/flytekit/unit/models/test_literals.py
Labels: lgtm, size:M

#2275 cache ignore portion
  flytekit/core/base_task.py
  flytekit/core/local_cache.py
  flytekit/core/task.py
  flytekit/models/task.py
  plugins/flytekit-bigquery/tests/test_agent.py
  plugins/flytekit-openai/tests/test_agent.py
  plugins/flytekit-snowflake/tests/test_agent.py
  plugins/flytekit-spark/tests/test_agent.py
  tests/flytekit/common/parameterizers.py
  tests/flytekit/unit/core/test_local_cache.py
  tests/flytekit/unit/models/test_tasks.py
  tests/flytekit/unit/models/test_workflow_closure.py
Labels: lgtm, size:L

#2283 Fix CI Error by restricting s3fs version
  pyproject.toml
Labels: lgtm, size:XS

#2273 Add support for Union[FlyteFile, FlyteDirectory] as input
  flytekit/types/directory/types.py
  flytekit/types/file/file.py
  tests/flytekit/unit/core/test_type_engine.py
Labels: lgtm, size:M

#2278 Update flyteinteractive Jupyter: Move to `ClassDecorator`
  plugins/flytekit-flyteinteractive/README.md
  plugins/flytekit-flyteinteractive/docs/jupyter_example.png
  plugins/flytekit-flyteinteractive/docs/vscode_example.png
  plugins/flytekit-flyteinteractive/flytekitplugins/flyteinteractive/__init__.py
  plugins/flytekit-flyteinteractive/flytekitplugins/flyteinteractive/constants.py
  plugins/flytekit-flyteinteractive/flytekitplugins/flyteinteractive/jupyter_lib/constants.py
  plugins/flytekit-flyteinteractive/flytekitplugins/flyteinteractive/jupyter_lib/decorator.py
  plugins/flytekit-flyteinteractive/flytekitplugins/flyteinteractive/jupyter_lib/jupyter_constants.py
  plugins/flytekit-flyteinteractive/flytekitplugins/flyteinteractive/utils.py
  plugins/flytekit-flyteinteractive/flytekitplugins/flyteinteractive/vscode_lib/config.py
  plugins/flytekit-flyteinteractive/flytekitplugins/flyteinteractive/vscode_lib/decorator.py
  plugins/flytekit-flyteinteractive/flytekitplugins/flyteinteractive/vscode_lib/vscode_constants.py
  plugins/flytekit-flyteinteractive/tests/test_flyteinteractive_jupyter.py
  plugins/flytekit-flyteinteractive/tests/test_flyteinteractive_vscode.py
Labels: lgtm, size:XL

#2291 stuff
  flytekit/core/array_node_map_task.py
  tests/flytekit/unit/core/test_array_node_map_task.py
Labels: size:M

#2288 Setting interruptible on ArrayNode sub node metadata
  flytekit/core/array_node_map_task.py
  tests/flytekit/unit/core/test_array_node_map_task.py
Labels: lgtm, size:M

#2269 Add extra-index-url to ImageSpec
  flytekit/image_spec/image_spec.py
  plugins/flytekit-envd/flytekitplugins/envd/image_builder.py
  plugins/flytekit-envd/tests/test_image_spec.py
  tests/flytekit/unit/cli/pyflyte/test_run.py
Labels: lgtm, size:M

#2285 pre-commit: upgrade hook `shellcheck-py`
  .pre-commit-config.yaml
Labels: lgtm, size:XS

#2294 Core/cli recover
  flytekit/clis/sdk_in_container/executions.py
  flytekit/clis/sdk_in_container/pyflyte.py
  tests/flytekit/unit/cli/pyflyte/test_executions.py
Labels: lgtm, size:L

#2027 Sagemaker inference agent
  .github/workflows/pythonbuild.yml
  .pre-commit-config.yaml
  Dockerfile.agent
  docs/source/plugins/awssagemaker.rst
  docs/source/plugins/awssagemaker_inference.rst
  docs/source/plugins/index.rst
  flytekit/core/base_task.py
  flytekit/core/condition.py
  flytekit/core/task.py
  plugins/README.md
  plugins/flytekit-airflow/flytekitplugins/airflow/task.py
  plugins/flytekit-aws-sagemaker/README.md
  plugins/flytekit-aws-sagemaker/dev-requirements.txt
  plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker/__init__.py
  plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker/distributed_training.py
  plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker/hpo.py
  plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker/models/__init__.py
  plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker/models/hpo_job.py
  plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker/models/parameter_ranges.py
  plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker/models/training_job.py
  plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker/training.py
  plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/__init__.py
  plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/agent.py
  plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/boto3_agent.py
  plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/boto3_mixin.py
  plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/boto3_task.py
  plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/task.py
  plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/workflow.py
  plugins/flytekit-aws-sagemaker/scripts/flytekit_sagemaker_runner.py
  plugins/flytekit-aws-sagemaker/setup.py
  plugins/flytekit-aws-sagemaker/tests/test_boto3_agent.py
  plugins/flytekit-aws-sagemaker/tests/test_boto3_mixin.py
  plugins/flytekit-aws-sagemaker/tests/test_boto3_task.py
  plugins/flytekit-aws-sagemaker/tests/test_flytekit_sagemaker_running.py
  plugins/flytekit-aws-sagemaker/tests/test_hpo.py
  plugins/flytekit-aws-sagemaker/tests/test_hpo_job.py
  plugins/flytekit-aws-sagemaker/tests/test_inference_agent.py
  plugins/flytekit-aws-sagemaker/tests/test_inference_task.py
  plugins/flytekit-aws-sagemaker/tests/test_inference_workflow.py
  plugins/flytekit-aws-sagemaker/tests/test_parameter_ranges.py
  plugins/flytekit-aws-sagemaker/tests/test_training.py
  plugins/flytekit-aws-sagemaker/tests/test_training_job.py
  plugins/flytekit-greatexpectations/flytekitplugins/great_expectations/schema.py
  plugins/flytekit-papermill/tests/test_task.py
  pyproject.toml
Labels: lgtm, size:XXL

#2272 Pass additional fields to agent create
  flytekit/extend/backend/agent_service.py
  flytekit/extend/backend/base_agent.py
  tests/flytekit/unit/extend/test_agent.py
Labels: lgtm, size:S

#2287 feat: Add retry mechanism to file access methods
  dev-requirements.in
  flytekit/core/data_persistence.py
Labels: lgtm, size:S

#2280 pyflyte run spark task
  flytekit/core/container_task.py
  flytekit/core/python_auto_container.py
  flytekit/remote/remote.py
  plugins/flytekit-spark/flytekitplugins/spark/task.py
Labels: lgtm, size:M

#2265 [CI] Add an action to remove cache from runners
  .github/actions/clear-action-cache/action.yml
  .github/workflows/pythonbuild.yml
Labels: lgtm, size:S

#2277 feat: Support ImageSpec as base image
  flytekit/image_spec/image_spec.py
  plugins/flytekit-envd/tests/test_image_spec.py
Labels: lgtm, size:S

#2293 Makes the deviceflow auth URL simplier
  flytekit/clients/auth/authenticator.py
Labels: lgtm, size:XS

#2282 Add task execution metadata to agent create
  flytekit/extend/backend/agent_service.py
  flytekit/extend/backend/base_agent.py
  flytekit/extend/backend/utils.py
  flytekit/models/task.py
  tests/flytekit/unit/extend/test_agent.py
Labels: lgtm, size:L

#2263 [flytekitplugins] Rename ChatGPT module to OpenAI module
  plugins/flytekit-openai/README.md
  plugins/flytekit-openai/flytekitplugins/openai/__init__.py
  plugins/flytekit-openai/flytekitplugins/openai/chatgpt/__init__.py
  plugins/flytekit-openai/flytekitplugins/openai/chatgpt/agent.py
  plugins/flytekit-openai/flytekitplugins/openai/chatgpt/task.py
  plugins/flytekit-openai/setup.py
  plugins/flytekit-openai/tests/__init__.py
  plugins/flytekit-openai/tests/test_chatgpt.py
Labels: lgtm, size:S

#1808 Add support for execution of reference entities
  flytekit/remote/remote.py
  tests/flytekit/integration/remote/test_remote.py
Labels: lgtm, size:L

#2300 Add serial marker to cache related tests
  tests/flytekit/unit/core/test_local_cache.py
Labels: lgtm, size:XS

#2298 feat: Support pep604 union operator
  flytekit/core/interface.py
  flytekit/core/type_engine.py
  plugins/flytekit-pydantic/flytekitplugins/pydantic/commons.py
  pyproject.toml
  tests/flytekit/unit/core/test_interface.py
  tests/flytekit/unit/core/test_type_engine.py
Labels: lgtm, size:M

#2301 Partition limit
  flytekit/core/artifact.py
  tests/flytekit/unit/core/test_artifacts.py
Labels: lgtm, size:S

#2302 Make artifact documentation visible
  flytekit/__init__.py
Labels: lgtm, size:S

#2308 remove secrets in sagemaker agent
  plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/agent.py
  plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/boto3_agent.py
  plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/boto3_mixin.py
  plugins/flytekit-aws-sagemaker/tests/test_boto3_agent.py
  plugins/flytekit-aws-sagemaker/tests/test_inference_agent.py
Labels: lgtm, size:M

#2274 Adapt flytekit ray plugin to kuberay 1.1.0
  plugins/flytekit-ray/flytekitplugins/ray/models.py
  plugins/flytekit-ray/flytekitplugins/ray/task.py
  plugins/flytekit-ray/tests/test_ray.py
Labels: lgtm, size:S

#2305 Remove post-execute hook from ray task
  plugins/flytekit-ray/flytekitplugins/ray/task.py
Labels: lgtm, size:XS

#2306 Gz encoding
  flytekit/types/file/file.py
  tests/flytekit/unit/core/test_data.py
  tests/flytekit/unit/core/test_flyte_file.py
Labels: lgtm, size:M

#2292 fix limit option
  flytekit/clis/sdk_in_container/run.py
Labels: lgtm, size:XS

#2310 Move SageMakerEndpointMetadata to agent.py
  flytekit/core/base_task.py
  plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/agent.py
  plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/task.py
Labels: lgtm, size:M

#2311 Add @samhita-alla to CODEOWNERS
  CODEOWNERS
Labels: lgtm, size:XS

#2312 Add way to create FlyteFile/Directory from remote location
  flytekit/types/directory/types.py
  flytekit/types/file/file.py
  tests/flytekit/unit/core/test_flyte_directory.py
  tests/flytekit/unit/core/test_flyte_file.py
Labels: lgtm, size:M
