Repository flyteorg/flytekit, pull requests merged in 2024-05, with the labels that each got.

#2349 Adds custom string format parameter to customize ImageSpec's tag
  flytekit/image_spec/image_spec.py
  tests/flytekit/unit/core/image_spec/test_image_spec.py
Labels: lgtm, size:S

#2370 Add optional execution metadata to objects written to storage for easy attribution
  flytekit/bin/entrypoint.py
  flytekit/configuration/__init__.py
  flytekit/configuration/internal.py
  flytekit/core/data_persistence.py
Labels: size:M

#2451 Make error messages in LaunchPlan.get_or_create actionable
  flytekit/core/launch_plan.py
Labels: error-message
