Repository flyteorg/flytekit, pull requests merged in 2024-04, with the labels that each got.

#2313 allow specifying version for the tritonserver image in sagemaker agent
  plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/__init__.py
  plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/boto3_mixin.py
  plugins/flytekit-aws-sagemaker/tests/test_boto3_mixin.py
Labels: lgtm, size:S

#2316 Ignore duplicate handler errors when lazy loading
  flytekit/core/type_engine.py
  flytekit/types/structured/structured_dataset.py
  tests/flytekit/unit/types/structured_dataset/test_structured_dataset.py
Labels: lgtm, size:M

#2317 Use correct plugin in agent image
  Dockerfile.agent
Labels: lgtm, size:XS

#2264 Add Python Dependency Deck
  .github/workflows/pythonbuild.yml
  Makefile
  flytekit/core/python_function_task.py
  flytekit/deck/renderer.py
  pyproject.toml
  tests/flytekit/unit/conftest.py
  tests/flytekit/unit/deck/test_deck.py
  tests/flytekit/unit/experimental/test_eager_workflows.py
Labels: lgtm, size:L

#2318 Ensure that annotations are dropped in the case of the dataclass and dict type transformers
  .github/workflows/pythonbuild.yml
  flytekit/core/type_engine.py
  tests/flytekit/unit/core/test_dataclass.py
  tests/flytekit/unit/core/test_type_engine.py
Labels: lgtm, size:L

#2290 refactor(core): Improve task module extraction logic
  flytekit/core/tracker.py
  flytekit/remote/remote.py
  plugins/flytekit-spark/tests/test_remote_register.py
Labels: lgtm, size:S

#2322 Run ignore query
  flytekit/clis/sdk_in_container/run.py
  flytekit/core/artifact.py
  flytekit/interaction/click_types.py
  tests/flytekit/unit/interaction/test_click_types.py
Labels: lgtm, size:L

#2279 Stop requiring users to import `dataclasses_json` or `DataClassJSONMixin` for dataclass
  flytekit/core/type_engine.py
  pyproject.toml
  tests/flytekit/unit/core/test_type_engine.py
  tests/flytekit/unit/core/test_type_hints.py
Labels: lgtm, size:L

#2286 Fix databricks job request serialization
  flytekit/models/task.py
Labels: lgtm, size:XS

#2329 Add name to union param
  flytekit/interaction/click_types.py
Labels: lgtm, size:XS

#2327 Remove typing-inspect dependency
  flytekit/core/type_engine.py
  pyproject.toml
Labels: lgtm, size:S

#2326 don't return triton image as a functools.partial
  plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/__init__.py
  plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/boto3_mixin.py
Labels: lgtm, size:S

#2324 Set a minimum version to mlflow in flytekit plugin
  .github/workflows/pythonbuild.yml
  plugins/flytekit-mlflow/setup.py
Labels: lgtm, size:XS

#2333 Show a dataproc link on FlyteConsole
  plugins/flytekit-airflow/flytekitplugins/airflow/agent.py
Labels: lgtm, size:M

#2334 [easy] Show `failed_node_id` in failure node local execution
  flytekit/core/workflow.py
  tests/flytekit/unit/core/test_workflows.py
Labels: lgtm, size:M

#2309 Log Agents In The Agent Server
  flytekit/clis/sdk_in_container/serve.py
  plugins/flytekit-snowflake/flytekitplugins/snowflake/agent.py
  tests/flytekit/unit/extend/test_agent.py
Labels: lgtm, size:M

#2331 Accept template strings for SQLAlchemyTask container_image
  flytekit/core/python_customized_container_task.py
  tests/flytekit/unit/core/test_shim_task.py
Labels: lgtm, size:S

#2337 Explicitly disallow iteration on Promises
  flytekit/core/promise.py
  tests/flytekit/unit/core/test_dynamic.py
Labels: lgtm, size:M

#2276 pyflyte `run`& `register` asynchronously
  flytekit/remote/remote.py
  flytekit/tools/repo.py
  tests/flytekit/integration/remote/test_remote.py
Labels: lgtm, size:L

#2347 Add ImageSpec reference docs to flyte docs
  docs/source/docs_index.rst
  docs/source/imagespec.rst
  flytekit/image_spec/__init__.py
Labels: lgtm, size:S

#2351 Consistent formatting for artifact id spec
  flytekit/core/artifact.py
  tests/flytekit/unit/core/test_data_persistence.py
  tests/flytekit/unit/types/pickle/test_flyte_pickle.py
Labels: lgtm, size:S

#2335 Support referencing docker images by digest in addition to by tag
  flytekit/configuration/__init__.py
  flytekit/core/python_auto_container.py
  plugins/flytekit-spark/tests/test_remote_register.py
  tests/flytekit/unit/cli/pyflyte/test_run.py
  tests/flytekit/unit/configuration/configs/sample.yaml
  tests/flytekit/unit/configuration/test_image_config.py
  tests/flytekit/unit/configuration/test_internal.py
  tests/flytekit/unit/core/test_context_manager.py
  tests/flytekit/unit/core/test_python_function_task.py
Labels: lgtm, size:L

#2340 Fix `_serialize_pod_spec` with no default image
  flytekit/core/utils.py
  tests/flytekit/unit/core/test_python_auto_container.py
Labels: lgtm, size:M

#2350 refactor: Improve logging and add caching to configs
  flytekit/clis/sdk_in_container/run.py
  flytekit/configuration/file.py
  flytekit/configuration/plugin.py
  flytekit/extend/backend/base_agent.py
  flytekit/loggers.py
  tests/flytekit/unit/configuration/test_image_config.py
  tests/flytekit/unit/core/test_data_persistence.py
  tests/flytekit/unit/remote/test_remote.py
Labels: lgtm, size:M

#2295 feat(pyflyte): Remove the limit that pyflyte can only run files in current and nested directories
  flytekit/clis/sdk_in_container/run.py
  tests/flytekit/unit/cli/pyflyte/test_run.py
Labels: lgtm, size:M

#2358 refactor: Improve error handling and logging
  flytekit/clis/sdk_in_container/run.py
  flytekit/exceptions/scopes.py
  flytekit/loggers.py
  plugins/conftest.py
  tests/flytekit/conftest.py
Labels: lgtm, size:M

#2258 Raw Container Task Local Execution
  flytekit/core/container_task.py
  tests/flytekit/unit/core/Dockerfile.raw_container
  tests/flytekit/unit/core/return_same_value.py
  tests/flytekit/unit/core/test_container_task.py
  tests/flytekit/unit/core/test_local_raw_container.py
  tests/flytekit/unit/core/write_flytedir.py
  tests/flytekit/unit/core/write_flytefile.py
Labels: lgtm, size:XL

#2354 Update template to link issue for closing
  pull_request_template.md
Labels: lgtm, size:S

#2268 Feature/array node workflow parallelism
  flytekit/core/array_node_map_task.py
  tests/flytekit/unit/core/test_array_node_map_task.py
Labels: lgtm, size:S

#2360 Removes cookiecutter dependency
  dev-requirements.in
  dev-requirements.txt
  flytekit/clis/sdk_in_container/init.py
  pyproject.toml
Labels: lgtm, size:L

#2355 Do not check for secret groups during runtime
  flytekit/configuration/plugin.py
  flytekit/core/context_manager.py
  tests/flytekit/unit/core/test_context_manager.py
  tests/flytekit/unit/models/core/test_security.py
Labels: lgtm, size:M

#2359 Use grpc metadata limit from Admin
  flytekit/clients/raw.py
Labels: lgtm, size:XS

#2364 use sphinx-design directives instead of sphinx-panels
  docs/source/extras.accelerators.rst
  flytekit/configuration/__init__.py
  flytekit/core/base_task.py
  flytekit/core/promise.py
  flytekit/core/python_function_task.py
  flytekit/core/type_engine.py
  flytekit/deck/__init__.py
  flytekit/extend/__init__.py
  flytekit/extras/accelerators.py
  flytekit/image_spec/__init__.py
  flytekit/testing/__init__.py
  flytekit/types/error/__init__.py
  flytekit/types/iterator/__init__.py
  flytekit/types/pickle/__init__.py
Labels: lgtm, size:M

#2367 Use default serialization settings if serialization_settings is None
  flytekit/models/admin/task_execution.py
  flytekit/remote/remote.py
Labels: size:S

#2369 Add .gitignore and .dockerignore behavior to ImageSpec
  flytekit/image_spec/image_spec.py
  flytekit/remote/executions.py
  flytekit/tools/fast_registration.py
  flytekit/tools/ignore.py
  plugins/flytekit-envd/flytekitplugins/envd/image_builder.py
  plugins/flytekit-envd/tests/.dockerignore
  plugins/flytekit-envd/tests/test_image_spec.py
  tests/flytekit/unit/cli/pyflyte/test_run.py
  tests/flytekit/unit/tools/test_fast_registration.py
  tests/flytekit/unit/tools/test_ignore.py
Labels: size:M

#2366 [Docs] Pyflyte package --output should say tar file
  flytekit/clis/sdk_in_container/register.py
Labels: lgtm, size:XS

#2356 Add default inputs to version hash
  flytekit/remote/remote.py
  tests/flytekit/integration/remote/test_remote.py
  tests/flytekit/integration/remote/workflows/basic/default_lp.py
  tests/flytekit/unit/remote/test_remote.py
Labels: size:M

#2252 Annotated StructuredDataset: support `nested_types`
  flytekit/types/structured/structured_dataset.py
  tests/flytekit/unit/types/structured_dataset/test_structured_dataset_workflow.py
  tests/flytekit/unit/types/structured_dataset/test_structured_dataset_workflow_with_nested_type.py
Labels: size:L

#2196 Improvement: accept int value for Resources
  flytekit/core/resources.py
  flytekit/core/utils.py
  tests/flytekit/unit/core/test_resources.py
  tests/flytekit/unit/core/test_type_hints.py
Labels: size:M
