Repository flyteorg/flytekit, pull requests merged in 2024-02, with the labels that each got.

#2181 Build python 3.12 default flytekit image
  .github/workflows/pythonpublish.yml
Labels: lgtm

#2169 Fix airflow sensor
  plugins/flytekit-airflow/flytekitplugins/airflow/task.py
  plugins/flytekit-airflow/tests/test_task.py
Labels: lgtm

#2141 Remove asynchronous flag from base agent
  flytekit/extend/backend/agent_service.py
  flytekit/extend/backend/base_agent.py
  flytekit/sensor/sensor_engine.py
  plugins/flytekit-airflow/flytekitplugins/airflow/agent.py
  plugins/flytekit-airflow/tests/test_agent.py
  plugins/flytekit-bigquery/flytekitplugins/bigquery/agent.py
  plugins/flytekit-bigquery/tests/test_agent.py
  plugins/flytekit-mmcloud/flytekitplugins/mmcloud/agent.py
  plugins/flytekit-snowflake/flytekitplugins/snowflake/agent.py
  plugins/flytekit-snowflake/tests/test_agent.py
  plugins/flytekit-spark/flytekitplugins/spark/agent.py
  plugins/flytekit-spark/tests/test_agent.py
  tests/flytekit/unit/extend/test_agent.py
  tests/flytekit/unit/sensor/test_sensor_engine.py
Labels: lgtm, size:L

#2159 Update Base Agent Logs by Rich Progress Feature
  flytekit/extend/backend/base_agent.py
Labels: lgtm, size:S

#2186 Fix Base Agent Input Bug
  flytekit/extend/backend/base_agent.py
Labels: lgtm, size:XS

#2185 Disable rich logger in the default image
  Dockerfile
  Dockerfile.dev
Labels: lgtm, size:XS

#2190 Enhance error logging in pyflyte
  flytekit/remote/remote.py
Labels: lgtm, size:XS

#2184 Do not lazy-load pyspark.ml
  plugins/flytekit-spark/flytekitplugins/spark/pyspark_transformers.py
Labels: lgtm, size:XS

#2192 Bump flyteidl to 1.10.7
  pyproject.toml
Labels: lgtm, size:XS

#2189 Extends config plugin API to customize the default OAuth success html
  flytekit/clients/auth/default_html.py
  flytekit/configuration/plugin.py
  tests/flytekit/unit/clients/auth/test_default_html.py
Labels: lgtm, size:M

#2195 Fix Airflow Agent kwargs bug
  plugins/flytekit-airflow/flytekitplugins/airflow/task.py
Labels: lgtm, size:XS

#2194 Container Image should be an input into computing the task version
  flytekit/remote/remote.py
  tests/flytekit/unit/remote/test_remote.py
Labels: lgtm, size:M

#2084 add executable to shell task
  flytekit/extras/tasks/shell.py
  tests/flytekit/unit/extras/tasks/test_shell.py
Labels: lgtm, size:M

#2202 feat(flyteinteractive): Disable workspace trust for vscode server
  plugins/flytekit-flyteinteractive/flytekitplugins/flyteinteractive/vscode_lib/decorator.py
Labels: lgtm, size:XS

#2198 Fix local overwrite cache
  flytekit/clis/sdk_in_container/run.py
  flytekit/configuration/__init__.py
  flytekit/configuration/internal.py
  flytekit/core/base_task.py
  flytekit/core/local_cache.py
  tests/flytekit/unit/core/test_local_cache.py
Labels: lgtm, size:M

#2200 docs(flyteinteractive): Change docker build to docker buildx build
  plugins/flytekit-flyteinteractive/README.md
Labels: lgtm, size:XS

#2199 Distribute tests by file
  .github/workflows/pythonbuild.yml
  Makefile
Labels: lgtm, size:XS

#2154 Support overridding cache configuration
  flytekit/core/node.py
  flytekit/models/core/workflow.py
  tests/flytekit/unit/core/test_node_creation.py
Labels: lgtm, size:M

#2029 [caching] Add overwrite_cache flag when creating launch plan
  flytekit/core/launch_plan.py
  flytekit/models/launch_plan.py
  flytekit/tools/translator.py
  tests/flytekit/unit/core/test_launch_plan.py
  tests/flytekit/unit/models/test_launch_plan.py
Labels: lgtm, size:M

#2205 pin great expectations version and run local cache tests serially
  Makefile
  plugins/flytekit-greatexpectations/setup.py
  pyproject.toml
  tests/flytekit/unit/core/test_local_cache.py
Labels: lgtm, size:M

#2218 Move agent (extend) tests to extras
  .github/workflows/pythonbuild.yml
  Makefile
Labels: lgtm, size:M

#2220 Fix CI error
  flytekit/extend/backend/base_agent.py
  plugins/flytekit-bigquery/flytekitplugins/bigquery/agent.py
  plugins/flytekit-bigquery/tests/test_agent.py
  plugins/flytekit-spark/flytekitplugins/spark/agent.py
  plugins/flytekit-spark/tests/test_agent.py
  tests/flytekit/unit/extend/test_agent.py
Labels: lgtm, size:M

#2222 upload files/directories when using remote-workflow
  flytekit/clis/sdk_in_container/run.py
Labels: lgtm, size:XS

#2219 CI Uses GITHUB_OUTPUT in github actions
  .github/workflows/pythonpublish.yml
Labels: lgtm, size:XS

#2204 Add launch condition column
  flytekit/core/artifact.py
  flytekit/core/launch_plan.py
  flytekit/core/schedule.py
  flytekit/models/schedule.py
  flytekit/tools/translator.py
  pyproject.toml
  tests/flytekit/unit/core/test_artifacts.py
Labels: lgtm, size:L

#2146 Add SyncAgentBase
  .github/workflows/pythonbuild.yml
  Dockerfile.dev
  Makefile
  dev-requirements.in
  flytekit/clis/sdk_in_container/serve.py
  flytekit/core/type_engine.py
  flytekit/extend/backend/agent_service.py
  flytekit/extend/backend/base_agent.py
  flytekit/extend/backend/utils.py
  flytekit/sensor/base_sensor.py
  flytekit/sensor/file_sensor.py
  flytekit/sensor/sensor_engine.py
  flytekit/types/file/file.py
  plugins/flytekit-airflow/flytekitplugins/airflow/agent.py
  plugins/flytekit-airflow/setup.py
  plugins/flytekit-airflow/tests/test_agent.py
  plugins/flytekit-aws-batch/setup.py
  plugins/flytekit-bigquery/flytekitplugins/bigquery/agent.py
  plugins/flytekit-bigquery/setup.py
  plugins/flytekit-bigquery/tests/test_agent.py
  plugins/flytekit-greatexpectations/setup.py
  plugins/flytekit-k8s-pod/setup.py
  plugins/flytekit-mmcloud/flytekitplugins/mmcloud/agent.py
  plugins/flytekit-mmcloud/tests/test_mmcloud.py
  plugins/flytekit-modin/setup.py
  plugins/flytekit-onnx-scikitlearn/setup.py
  plugins/flytekit-papermill/dev-requirements.in
  plugins/flytekit-snowflake/flytekitplugins/snowflake/agent.py
  plugins/flytekit-snowflake/setup.py
  plugins/flytekit-snowflake/tests/test_agent.py
  plugins/flytekit-spark/flytekitplugins/spark/agent.py
  plugins/flytekit-spark/setup.py
  plugins/flytekit-spark/tests/test_agent.py
  pyproject.toml
  tests/flytekit/integration/remote/test_remote.py
  tests/flytekit/unit/extend/test_agent.py
  tests/flytekit/unit/sensor/test_file_sensor.py
  tests/flytekit/unit/sensor/test_sensor_engine.py
Labels: lgtm, size:XXL
